### PR TITLE
Common.DraftRoot: ShareAction

### PR DESCRIPTION
**Pull request by ralfhandl**
- [ ] Can draft documents only be shared as a whole, or is it possible to share only a sub-tree of a draft document?

### CODE REVIEW

**Review by martin4all — APPROVED** [review]
Ok

**Review by martin4all — DISMISSED** [review]
Ok

**Review by RaizoC — DISMISSED** [review]

**Review by martin4all — APPROVED** [review]
Ok

**Review by BerSie — COMMENTED** [review]
What is the logic of the Users list? If I send the ShareAction request twice with different users - does the second list win, or is it cumulative? And related to this question: will there be an unshare or a share with an empty list?

**Comment by ralfhandl** [comment]
> What is the logic of the Users list? If I send the ShareAction request twice with different users - does the second list win, or is it cumulative? And related to this question: will there be an unshare or a share with an empty list?

@martin4all @RaizoC can you please answer this question?

**Comment by RaizoC** [comment]
> > What is the logic of the Users list? If I send the ShareAction request twice with different users - does the second list win, or is it cumulative? And related to this question: will there be an unshare or a share with an empty list?
> 
> @martin4all @RaizoC can you please answer this question?

I think it was defined that the list is always complete, i.e not cumulative. Thus, calling the share action without any users will logically un-share the draft, i.e. it is not shared with anybody. Calling the action within one request multiple times lets the last one win, while within one change set it is not deterministic which one wins. The behavior is thus similar if you send a PATCH request for the same instance on the same property where only one wins.

**Review by RaizoC — APPROVED** [review]

**Review by BerSie — APPROVED** [review]

**Pull request merged**
