### PR TITLE
Hierarchical line items

### PR DESCRIPTION
**Pull request by BerSie**
This is PR is about the possibility to apply a hierarchy (and later one aggregation ) on existing list definition (aka UI.LineItem). We start with three different proposals: adding a new property to UI.PresentationVariant, adding a new term that can be applied on UI.LineItem annotations, adding a new term that uses UI.LineItem as BaseTerm.

### CODE REVIEW

**Comment by nlunets** [comment]
I like option 1 and 2, with the first one being my preferred (additional property on the PV). But i do see the value of the first one in case people don't want to go through the trouble of defining one.

**Comment by vescalier** [comment]
Option 1 is my favorite, and I find option 3 a little bit cumbersome

**Comment by HeikoTheissen** [comment]
I am fine with option 1.

**Comment by BerSie** [comment]
Thanks for judging and voting! I removed variant 2 and 3. Please review - thanks!

**Review by nlunets — APPROVED** [review]

**Review by HeikoTheissen — APPROVED** [review]

**Review by ralfhandl — DISMISSED** [review]

**Review by ralfhandl — APPROVED** [review]

**Pull request merged**
