### PR TITLE
Changing type of Margin, Border, FitToPage, FontSize, & FontName

### PR DESCRIPTION
**Pull request by bernhardgr42**
Margin, Border, FitToPage, FontSize, & FontName are new features of the PDF_API. The annotation shows you if this option is available from the server.
=> Changing the types to boolean.

We have no default FontName, FonstSize and so on. Only the pdf API knows this. If the pdf API add this default knowledge, it could be (for an older FES), that this information is not available. Then we would have to set NULL for these default FontName, FontSize, etc. setting. Therefore, I would not add this here.

### CODE REVIEW

**Review by uhlmannm — APPROVED** [review]

**Comment by bernhardgr42** [comment]
> 

We will add this to the DocDescr for sure.

**Review by simlin — APPROVED** [review]

**Comment by HerzogIgzorn** [comment]
Beside some minor description issues, it's fine.

**Review by bernhardgr42 — COMMENTED** [review]
Remove: Remove "a the" from the description.

**Review by HerzogIgzorn — APPROVED** [review]
Now it is fine

**Review by ralfhandl — APPROVED** [review]

**Comment by ralfhandl** [comment]
@uhlmannm @simlin please add your reviews

**Review by uhlmannm — APPROVED** [review]

**Pull request merged**
