### PR TITLE
Fix: reference Aggregation and Analytics vocabularies in UI vocabulary

### PR DESCRIPTION
**Pull request by ralfhandl**
Validation.AllowedTerms references terms from these vocabularies

### CODE REVIEW

**Review by UweSchwerk — CHANGES_REQUESTED** [review]
What about Common - it had a similar issue ?

**Comment by HeikoTheissen** [comment]
> What about Common - it had a similar issue ? (Common.SortOrderType/DynamicProperty)

The Common vocabulary is already referenced in the UI vocabulary.

**Review by HeikoTheissen — APPROVED** [review]

**Comment by ralfhandl** [comment]
And the UI vocabulary is referenced from Common.

**Comment by BerSie** [comment]
Hmm, I would expect that the Analytics vocabulary should be referenced explicitly if a term if this vocabulary is used. So, I think, Uwe is right.

**Comment by ralfhandl** [comment]
> `Common.SortOrderType/DynamicProperty` is annotated with `Validation.AllowedTerms` containing `Analytics.AggregatedProperty` - even though `Analytics` is not defined

Thanks, I missed that one, reference added.

**Review by UweSchwerk — APPROVED** [review]

**Review by HeikoTheissen — APPROVED** [review]

**Review by HeikoTheissen — APPROVED** [review]

**Pull request merged**
